[project]
name = "backend-blazetrack"
version = "0.1.0"
description = "Production ready BlazeTrack"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.140.0",
    "geopy>=2.5.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "uvicorn>=0.51.0",
]
